<a href="https://colab.research.google.com/github/github4xyz/YGL/blob/main/01_Iris_data_EDA/00_P1_Iris_data_basic_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Log*
Started on 0506



# Iris data analysis

Motivation:




Data analysis = EDA. before EDA, CDA (Confirmatory Data Analysis)



Planning:


Progress:


Revised/adjustment:


Lessons learnt:




Resource:

Name | Links | Priority
--- | --- | ---
**[MAIN]** Data Science Example - Iris dataset (R) | [Link](http://www.lac.inpe.br/~rafael.santos/Docs/CAP394/WholeStory-Iris.html) | Primary
Machine Learning with Iris Dataset | [Link](https://www.kaggle.com/jchen2186/machine-learning-with-iris-dataset) | Secondary
ML with Iris Dataset (RitchieNg) | [Link](https://www.ritchieng.com/machine-learning-iris-dataset/) | Secondary
Exploring Classifiers with Python Scikit-learn — Iris Dataset | [Link](https://towardsdatascience.com/exploring-classifiers-with-python-scikit-learn-iris-dataset-2bcb490d2e1b) | Primary
Visualizing decision tree | [Link](https://towardsdatascience.com/search?q=visualizing%20decision%20tree) | Primary
Visualize a Decision Tree in 4 Ways with Scikit-Learn and Python | [Link](https://towardsdatascience.com/search?q=visualizing%20decision%20tree) | Primary
Iris data on Wiki | [Link](https://en.wikipedia.org/wiki/Iris_flower_data_set) | Secondary
**[Important]** Scikit-Learn Iris data Exploratory | [Link](https://www.kaggle.com/lalitharajesh/iris-dataset-exploratory-data-analysis) | Primary





## Iris data set

## Scikit-Learn data details from 
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html# 


In [ ]:
# import load_iris function from datasets module
# convention is to import modules instead of sklearn as a whole
from sklearn.datasets import load_iris

In [ ]:
# save "bunch" object containing iris dataset and its attributes
# the data type is "bunch"
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [ ]:
# print the iris data
# same data as shown previously
# each row represents each sample
# each column represents the features
print(iris.data)

In [ ]:
# print integers representing the species of each observation
# 0, 1, and 2 represent different species
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
# print the names of the four features
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
# print the encoding scheme for species: 0 = setosa, 1 = versicolor, 2 = virginica
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [ ]:
# check the types of the features and response
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# check the shape of the features (first dimension = number of observations, second dimensions = number of features)
print(iris.data.shape)

(150, 4)


In [ ]:
# check the shape of the response (single dimension matching the number of observations)
print(iris.target.shape)

(150,)


In [ ]:
# this ndarray can directly used for ploting!!!
# but not so easy for data exploring/observing.

# store feature matrix in "X"
X = iris.data

# store response vector in "y"
y = iris.target

# print(X)
# print(y)

# Into DataFrame

pandas DataFrame offers few statistical functions as following


In [ ]:
# Transforming ndarraies into DataFrames
# 

import numpy as np
import pandas as pd

# Creating pandas Data Frame with Iris (Data Type Bunch (ndarray)) above
# Combining the two data and target arraies into iris_df
# Column labels with feature names and target
# replace 0, 1, 2 with appropriate iris type
iris_df = pd.DataFrame(data= np.c_[iris['data'], iris['target']], columns= iris['feature_names'] + ['target'])
iris_df['target'] = iris_df['target'].map({0:"setosa", 1:"versicolor", 2:"virginica"})

# Prepairing the Data Frame for Plotting
# Sepal/Petal Length/Width = X, Iris Type = y
X_iris_df = iris_df.iloc[:,:-1]
y_iris_df = iris_df.iloc[:,[-1]]

In [ ]:
# Check the data type of new data
print(type(iris_df))

# 5 from the beginning of the DF
iris_df.head()

<class 'pandas.core.frame.DataFrame'>


sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2  setosa
1                4.9               3.0  ...               0.2  setosa
2                4.7               3.2  ...               0.2  setosa
3                4.6               3.1  ...               0.2  setosa
4                5.0               3.6  ...               0.2  setosa

[5 rows x 5 columns]

In [ ]:
# 5 from the end of the DF
iris_df.tail()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)     target
145                6.7               3.0  ...               2.3  virginica
146                6.3               2.5  ...               1.9  virginica
147                6.5               3.0  ...               2.0  virginica
148                6.2               3.4  ...               2.3  virginica
149                5.9               3.0  ...               1.8  virginica

[5 rows x 5 columns]

In [ ]:
# check non-null data and data type of each features and target
# Mememory usage

iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
# Basic statistical descriptions
# Count, Mean, Standard deviation, Minimum, inter quatiles, Maximum of each features

iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count         150.000000        150.000000         150.000000        150.000000
mean            5.843333          3.057333           3.758000          1.199333
std             0.828066          0.435866           1.765298          0.762238
min             4.300000          2.000000           1.000000          0.100000
25%             5.100000          2.800000           1.600000          0.300000
50%             5.800000          3.000000           4.350000          1.300000
75%             6.400000          3.300000           5.100000          1.800000
max             7.900000          4.400000           6.900000          2.500000

In [ ]:
# Basic statistical descriptions
# Count, Mean, Standard deviation, Minimum, inter quatiles, Maximum of each features
# those are only for numeric data types
# For all data, including none-numerial column such as 'target'

# Note: unique, top, frequency are only for object data type

iris_df.describe(include='all')


sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
count          150.000000        150.000000  ...        150.000000     150
unique                NaN               NaN  ...               NaN       3
top                   NaN               NaN  ...               NaN  setosa
freq                  NaN               NaN  ...               NaN      50
mean             5.843333          3.057333  ...          1.199333     NaN
std              0.828066          0.435866  ...          0.762238     NaN
min              4.300000          2.000000  ...          0.100000     NaN
25%              5.100000          2.800000  ...          0.300000     NaN
50%              5.800000          3.000000  ...          1.300000     NaN
75%              6.400000          3.300000  ...          1.800000     NaN
max              7.900000          4.400000  ...          2.500000     NaN

[11 rows x 5 columns]

In [ ]:
# Fastest way to find if there is any missing values
# iris_df.isnull().values.any()

# Display if there is any NaN values in the DF
iris_df.isnull().sum()

# alternative
# iris_df.apply(lambda x: sum(x.isnull()),axis=0)


sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [ ]:
# count of each value of targets
#

iris_df['target'].value_counts()

setosa        50
virginica     50
versicolor    50
Name: target, dtype: int64

In [ ]:
# Basic statistical descriptions for object data type
# unique, top, frequency 

iris_df.describe(include=['object'])


target
count      150
unique       3
top     setosa
freq        50

In [ ]:
# Displaying DataFrame for Plotting
# Note: the shape of the data 
# [150 rows x 4 columns] and [150 rows x 1 columns]

print(X_iris_df)
print(y_iris_df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]
        target
0       setosa
1       se

In [ ]:
# Rearrange DataFrame grouped by target for 
# Basic statistical descriptions 

setosa=iris_df[iris_df['target']=='setosa']
versicolor =iris_df[iris_df['target']=='versicolor']
virginica =iris_df[iris_df['target']=='virginica']

print(setosa.describe())
print(versicolor.describe())
print(virginica.describe())

       sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count           50.00000         50.000000          50.000000         50.000000
mean             5.00600          3.428000           1.462000          0.246000
std              0.35249          0.379064           0.173664          0.105386
min              4.30000          2.300000           1.000000          0.100000
25%              4.80000          3.200000           1.400000          0.200000
50%              5.00000          3.400000           1.500000          0.200000
75%              5.20000          3.675000           1.575000          0.300000
max              5.80000          4.400000           1.900000          0.600000
       sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count          50.000000         50.000000          50.000000         50.000000
mean            5.936000          2.770000           4.260000          1.326000
std             0.516171          0.3137

# Few other Statistical explore in Python

## scipy.stats.describe

In [ ]:
# using scipy to perform a summary (describe)

from scipy import stats

stats.describe(X, ddof=1, bias=False)

DescribeResult(nobs=150, minmax=(array([4.3, 2. , 1. , 0.1]), array([7.9, 4.4, 6.9, 2.5])), mean=array([5.84333333, 3.05733333, 3.758     , 1.19933333]), variance=array([0.68569351, 0.18997942, 3.11627785, 0.58100626]), skewness=array([ 0.31491096,  0.31896566, -0.27488418, -0.10296675]), kurtosis=array([-0.55206404,  0.22824904, -1.40210342, -1.340604  ]))

In [ ]:
# In addtition to pandas describe,
# it provides variance, skewness, kurtosis

result = stats.describe(X, ddof=1, bias=False)

print(result.nobs)
print(result.minmax[0])  # Min
print(result.minmax[1])  # Max
print(result.mean)
print(result.variance)
print(result.skewness)
print(result.kurtosis)

150
[4.3 2.  1.  0.1]
[7.9 4.4 6.9 2.5]
[5.84333333 3.05733333 3.758      1.19933333]
[0.68569351 0.18997942 3.11627785 0.58100626]
[ 0.31491096  0.31896566 -0.27488418 -0.10296675]
[-0.55206404  0.22824904 -1.40210342 -1.340604  ]


## Measures of Correlation Between Pairs of Data




You’ll see the following measures of correlation between pairs of data:

* **Positive correlation** exists when larger values of 𝑥 correspond to larger values of 𝑦 and vice versa.
* **Negative correlation** exists when larger values of 𝑥 correspond to smaller values of 𝑦 and vice versa.
* **Weak or no correlation exists** if there is no such apparent relationship.

---



![Picture](https://files.realpython.com/media/py-stats-08.5a1e9f3e3aa4.png )

From https://realpython.com/python-statistics/


The two statistics that measure the correlation between datasets are **covariance** and the **correlation coefficient** 

Might need to convert the data to NumPy arrays and/or Pandas Series
* NumPy has the function cov() that returns the covariance matrix:

## Correlation Coefficient 

The **correlation coefficient**, or **Pearson product-moment correlation coefficient**, is denoted by the symbol 𝑟. The coefficient is another measure of the correlation between data. You can think of it as a standardized covariance. Here are some important facts about it:

* The **value 𝑟 > 0** indicates positive correlation.
* The **value 𝑟 < 0** indicates negative correlation.
* The **value r = 1** is the maximum possible value of 𝑟. It corresponds to a perfect positive linear relationship between variables.
* The **value r = −1** is the minimum possible value of 𝑟. It corresponds to a perfect negative linear relationship between variables.
* The **value r ≈ 0, or when 𝑟 is around zero**, means that the correlation between variables is weak.

```
r, p = scipy.stats.pearsonr(x_, y_)
```


correlation coefficient matrix

```
corr_matrix = np.corrcoef(x_, y_)      #numpy

# or

scipy.stats.linregress(x_, y_)   # rvalue = correlation coefficient

# or 

r = x__.corr(y__)    # pandas
```


