# Pandas

Series - very similar to dictionary

In [1]:
import pandas as pd

In [2]:
a = {'a':10, 'b':20, 'c':30,'d':40,'e':50}

In [3]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [4]:
type(a)

dict

In [5]:
b = pd.Series(a)

In [6]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [7]:
type(b)

pandas.core.series.Series

In [8]:
b.shape

(5,)

In [9]:
import numpy as np

In [10]:
aa = np.arange(3,10)

In [11]:
aa

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
bb = pd.Series(aa)

In [13]:
bb

0    3
1    4
2    5
3    6
4    7
5    8
6    9
dtype: int64

In [14]:
bb.shape

(7,)

In [15]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [16]:
a.keys()

dict_keys(['a', 'b', 'c', 'd', 'e'])

In [17]:
a.values()

dict_values([10, 20, 30, 40, 50])

In [18]:
b 

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [19]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [20]:
b.values

array([10, 20, 30, 40, 50])

In [21]:
c = [10, 20, 30, 40, 50]

In [22]:
d = pd.Series(c)

In [23]:
d

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [24]:
type(d)

pandas.core.series.Series

In [25]:
pd.Series({'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50})

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [26]:
d.shape

(5,)

In [27]:
d.index

RangeIndex(start=0, stop=5, step=1)

In [28]:
d.values

array([10, 20, 30, 40, 50])

In [29]:
e = ['a','b','c','d','e']

In [30]:
f = [10,20,30,40,50]

In [31]:
g = pd.Series(f,index=e)

In [32]:
g

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [33]:
g['a']

10

In [34]:
g[0]

10

In [35]:
g['a':'d']

a    10
b    20
c    30
d    40
dtype: int64

In [36]:
g[0:4]

a    10
b    20
c    30
d    40
dtype: int64

DF

In [37]:
a = {'a':[1,2,3], 'b':[1,3,5], 'c':[2,4,6], 'd':[3,6,9]}

In [38]:
a

{'a': [1, 2, 3], 'b': [1, 3, 5], 'c': [2, 4, 6], 'd': [3, 6, 9]}

In [39]:
df1 = pd.DataFrame(a)

In [40]:
df1

a  b  c  d
0  1  1  2  3
1  2  3  4  6
2  3  5  6  9

In [41]:
type(df1)

pandas.core.frame.DataFrame

In [42]:
df1.shape

(3, 4)

In [43]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
 3   d       3 non-null      int64
dtypes: int64(4)
memory usage: 224.0 bytes


In [44]:
b = np.arange(12).reshape(3,4)

In [45]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
df2 = pd.DataFrame(b)

In [47]:
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [48]:
type(df2)

pandas.core.frame.DataFrame

In [49]:
df2.shape

(3, 4)

In [50]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
 1   1       3 non-null      int64
 2   2       3 non-null      int64
 3   3       3 non-null      int64
dtypes: int64(4)
memory usage: 224.0 bytes


In [90]:
df = pd.DataFrame([[1,20,'seoul'],[2,25,'deajeon']],
                  index = ['hong', 'gil'],
                  columns = ['order', 'age', 'area'])

In [91]:
df

order  age     area
hong      1   20    seoul
gil       2   25  deajeon

In [92]:
type(df)

pandas.core.frame.DataFrame

In [93]:
df.shape

(2, 3)

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, hong to gil
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   order   2 non-null      int64 
 1   age     2 non-null      int64 
 2   area    2 non-null      object
dtypes: int64(2), object(1)
memory usage: 64.0+ bytes


In [95]:
df.index

Index(['hong', 'gil'], dtype='object')

In [96]:
df.values

array([[1, 20, 'seoul'],
       [2, 25, 'deajeon']], dtype=object)

In [97]:
df.columns

Index(['order', 'age', 'area'], dtype='object')

In [98]:
df.index = ['ppl1', 'ppl2']

In [99]:
df

order  age     area
ppl1      1   20    seoul
ppl2      2   25  deajeon

In [100]:
df.columns = ['num', 'yearsold','city']

In [101]:
df

num  yearsold     city
ppl1    1        20    seoul
ppl2    2        25  deajeon

In [102]:
df = df.rename(index = {'ppl1':'hong'})

In [103]:
df

num  yearsold     city
hong    1        20    seoul
ppl2    2        25  deajeon

In [104]:
df = df.rename(columns={'num':'order', 'yearsold':'age'})

In [105]:
df

order  age     city
hong      1   20    seoul
ppl2      2   25  deajeon

In [106]:
df.loc['ppl3'] = [3,30,'pusan']

In [107]:
df.loc['ppl4'] = 0

In [108]:
df

order  age     city
hong      1   20    seoul
ppl2      2   25  deajeon
ppl3      3   30    pusan
ppl4      0    0        0

In [109]:
df.loc['ppl1'] = df.loc['hong']

In [110]:
df

order  age     city
hong      1   20    seoul
ppl2      2   25  deajeon
ppl3      3   30    pusan
ppl4      0    0        0
ppl1      1   20    seoul

In [111]:
df['agerange'] = ['20\'s','20\'s','30\'s', '0\'s', '20\'s']

In [112]:
df

order  age     city agerange
hong      1   20    seoul     20's
ppl2      2   25  deajeon     20's
ppl3      3   30    pusan     30's
ppl4      0    0        0      0's
ppl1      1   20    seoul     20's

In [113]:
df['prof']= 'student'

In [114]:
df

order  age     city agerange     prof
hong      1   20    seoul     20's  student
ppl2      2   25  deajeon     20's  student
ppl3      3   30    pusan     30's  student
ppl4      0    0        0      0's  student
ppl1      1   20    seoul     20's  student

In [115]:
df.loc['ppl4','order'] =4

In [116]:
df

order  age     city agerange     prof
hong      1   20    seoul     20's  student
ppl2      2   25  deajeon     20's  student
ppl3      3   30    pusan     30's  student
ppl4      4    0        0      0's  student
ppl1      1   20    seoul     20's  student

In [117]:
df.iloc[3,1]=10

In [118]:
df

order  age     city agerange     prof
hong      1   20    seoul     20's  student
ppl2      2   25  deajeon     20's  student
ppl3      3   30    pusan     30's  student
ppl4      4   10        0      0's  student
ppl1      1   20    seoul     20's  student

In [119]:
df.loc['ppl4',['city','agerange']] = 'kwangju', '10\'s'

In [120]:
df

order  age     city agerange     prof
hong      1   20    seoul     20's  student
ppl2      2   25  deajeon     20's  student
ppl3      3   30    pusan     30's  student
ppl4      4   10  kwangju     10's  student
ppl1      1   20    seoul     20's  student

In [121]:
df.iloc[3,[1,3]]=40,'40\'s'

In [122]:
df

order  age     city agerange     prof
hong      1   20    seoul     20's  student
ppl2      2   25  deajeon     20's  student
ppl3      3   30    pusan     30's  student
ppl4      4   40  kwangju     40's  student
ppl1      1   20    seoul     20's  student

In [123]:
df = df.drop('ppl4',axis = 0)

In [124]:
df

order  age     city agerange     prof
hong      1   20    seoul     20's  student
ppl2      2   25  deajeon     20's  student
ppl3      3   30    pusan     30's  student
ppl1      1   20    seoul     20's  student

In [125]:
df =df.drop(['agerange', 'prof'], axis = 1)

In [126]:
df

order  age     city
hong      1   20    seoul
ppl2      2   25  deajeon
ppl3      3   30    pusan
ppl1      1   20    seoul

pandas의 2차원 자료형 – DataFrame(3)

In [129]:
df2 = df

In [130]:
df2.loc['ppl1','order' ]=4

In [131]:
df

order  age     city
hong      1   20    seoul
ppl2      2   25  deajeon
ppl3      3   30    pusan
ppl1      4   20    seoul

In [132]:
df

order  age     city
hong      1   20    seoul
ppl2      2   25  deajeon
ppl3      3   30    pusan
ppl1      4   20    seoul

In [133]:
df3 = df.copy()

In [134]:
df3

order  age     city
hong      1   20    seoul
ppl2      2   25  deajeon
ppl3      3   30    pusan
ppl1      4   20    seoul

In [135]:
df3.loc['ppl1', 'order']=5

In [136]:
df3

order  age     city
hong      1   20    seoul
ppl2      2   25  deajeon
ppl3      3   30    pusan
ppl1      5   20    seoul

In [137]:
df

order  age     city
hong      1   20    seoul
ppl2      2   25  deajeon
ppl3      3   30    pusan
ppl1      4   20    seoul

In [138]:
hong = df.loc['hong']

In [139]:
hong

order        1
age         20
city     seoul
Name: hong, dtype: object

In [140]:
type(hong)

pandas.core.series.Series

In [141]:
hong.shape

(3,)

In [142]:
gil = df.iloc[0]

In [143]:
gil

order        1
age         20
city     seoul
Name: hong, dtype: object

In [144]:
type(gil)

pandas.core.series.Series

In [145]:
gil.shape

(3,)

In [146]:
df4 = df.loc[['hong', 'ppl1']]

In [147]:
df4

order  age   city
hong      1   20  seoul
ppl1      4   20  seoul

In [148]:
type(df4)

pandas.core.frame.DataFrame

In [149]:
df5 = df.iloc[[0,3]]

In [150]:
df5

order  age   city
hong      1   20  seoul
ppl1      4   20  seoul

In [151]:
df6 = df.loc['hong':'ppl3']

In [152]:
df6

order  age     city
hong      1   20    seoul
ppl2      2   25  deajeon
ppl3      3   30    pusan

In [153]:
df7 = df.iloc[0:3]

In [154]:
df7

order  age     city
hong      1   20    seoul
ppl2      2   25  deajeon
ppl3      3   30    pusan

In [155]:
df

order  age     city
hong      1   20    seoul
ppl2      2   25  deajeon
ppl3      3   30    pusan
ppl1      4   20    seoul

In [156]:
df8 = df[['age']]

In [157]:
df8

age
hong   20
ppl2   25
ppl3   30
ppl1   20

In [158]:
df9 = df['age']

In [159]:
df9

hong    20
ppl2    25
ppl3    30
ppl1    20
Name: age, dtype: int64

In [160]:
type(df8)

pandas.core.frame.DataFrame

In [161]:
type(df9)

pandas.core.series.Series

In [162]:
df10 = df[['age','city']]

In [163]:
df10

age     city
hong   20    seoul
ppl2   25  deajeon
ppl3   30    pusan
ppl1   20    seoul

In [164]:
df

order  age     city
hong      1   20    seoul
ppl2      2   25  deajeon
ppl3      3   30    pusan
ppl1      4   20    seoul

In [166]:
df11 = df.loc[['hong','ppl1'], ['age','city']]

In [167]:
df11

age   city
hong   20  seoul
ppl1   20  seoul

In [171]:
df12 = df.iloc[[0,3],[1,2]]

In [172]:
df12

age   city
hong   20  seoul
ppl1   20  seoul

In [173]:
a = {'name':['hong', 'ppl1','ppl2'], 'age':[20,30,25], 'city':['seoul','seoul', 'Deajeon']}

In [174]:
df = pd.DataFrame(a)

In [175]:
df

name  age     city
0  hong   20    seoul
1  ppl1   30    seoul
2  ppl2   25  Deajeon

In [176]:
df2 = df.set_index(['name'])

In [177]:
df2

age     city
name              
hong   20    seoul
ppl1   30    seoul
ppl2   25  Deajeon

In [178]:
df3 = df2.set_index(['city'])

In [179]:
df3

age
city        
seoul     20
seoul     30
Deajeon   25

In [180]:
df2

age     city
name              
hong   20    seoul
ppl1   30    seoul
ppl2   25  Deajeon

In [181]:
df3 = df2.reset_index()

In [182]:
df3

name  age     city
0  hong   20    seoul
1  ppl1   30    seoul
2  ppl2   25  Deajeon

In [183]:
df3 = df3.set_index(['city'])

In [184]:
df3

name  age
city              
seoul    hong   20
seoul    ppl1   30
Deajeon  ppl2   25

In [185]:
df2

age     city
name              
hong   20    seoul
ppl1   30    seoul
ppl2   25  Deajeon

In [186]:
df2 = df2.sort_index(ascending=True)

In [187]:
df2

age     city
name              
hong   20    seoul
ppl1   30    seoul
ppl2   25  Deajeon

In [188]:
df2 = df2.sort_index(ascending=False)

In [189]:
df2

age     city
name              
ppl2   25  Deajeon
ppl1   30    seoul
hong   20    seoul

In [190]:
df2 = df2.sort_values(by='age', ascending=True)

In [191]:
df2

age     city
name              
hong   20    seoul
ppl2   25  Deajeon
ppl1   30    seoul

In [192]:
df2 = df2.sort_values(by='age', ascending=False)

In [193]:
df2

age     city
name              
ppl1   30    seoul
ppl2   25  Deajeon
hong   20    seoul

In [194]:
df2 = df2.T

In [195]:
df2

name   ppl1     ppl2   hong
age      30       25     20
city  seoul  Deajeon  seoul

In [196]:
df2 = df2.T

In [197]:
df2

age     city
name             
ppl1  30    seoul
ppl2  25  Deajeon
hong  20    seoul

In [201]:
df2['agerange']=['30\'s', '20\'s', '20\'s']

In [202]:
df2

age     city agerange
name                      
ppl1  30    seoul     30's
ppl2  25  Deajeon     20's
hong  20    seoul     20's

In [203]:
b = {'30\'s':3, '20\'s':2}

In [204]:
df2['agerange'] = df2['agerange'].map(b)

In [205]:
df2

age     city  agerange
name                       
ppl1  30    seoul         3
ppl2  25  Deajeon         2
hong  20    seoul         2

In [206]:
a = {'a':10, 'b':20, 'c':30, 'd':40, 'e':50}

In [207]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [208]:
b = pd.Series(a)

In [209]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [210]:
type(b)

pandas.core.series.Series

In [211]:
c = b /10

In [212]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [213]:
c

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64

In [214]:
d = b + c

In [215]:
d

a    11.0
b    22.0
c    33.0
d    44.0
e    55.0
dtype: float64

In [216]:
e = {'a': 10,  'c': 20,  'e': 30, 'g':40}

In [217]:
e

{'a': 10, 'c': 20, 'e': 30, 'g': 40}

In [218]:
f = pd.Series(e)

In [219]:
f

a    10
c    20
e    30
g    40
dtype: int64

In [220]:
d+f

a    21.0
b     NaN
c    53.0
d     NaN
e    85.0
g     NaN
dtype: float64

In [221]:
d.add(f,fill_value = 0)

a    21.0
b    22.0
c    53.0
d    44.0
e    85.0
g    40.0
dtype: float64

In [222]:
d.sub(f,fill_value = 0)

a     1.0
b    22.0
c    13.0
d    44.0
e    25.0
g   -40.0
dtype: float64

In [224]:
d.mul(f,fill_value = 1)

a     110.0
b      22.0
c     660.0
d      44.0
e    1650.0
g      40.0
dtype: float64

In [226]:
d.div(f,fill_value = 0)

a    1.100000
b         inf
c    1.650000
d         inf
e    1.833333
g    0.000000
dtype: float64

In [227]:
d.div(f,fill_value = 1)

a     1.100000
b    22.000000
c     1.650000
d    44.000000
e     1.833333
g     0.025000
dtype: float64

In [228]:
a = {'score1':[10,20,30], 'score2':[20,40,60]}

In [229]:
df1 = pd.DataFrame(a)

In [230]:
b = {'score1':[100,200,300], 'score3':[200,400,600]}

In [231]:
df2 = pd.DataFrame(b)

In [232]:
df3 = df1 + df2

In [233]:
df3

score1  score2  score3
0     110     NaN     NaN
1     220     NaN     NaN
2     330     NaN     NaN

In [234]:
df4 = df1.add(df2, fill_value=0)

In [235]:
df4

score1  score2  score3
0     110    20.0   200.0
1     220    40.0   400.0
2     330    60.0   600.0

In [236]:
df5 = df1.sub(df2, fill_value=0)

In [237]:
df5

score1  score2  score3
0     -90    20.0  -200.0
1    -180    40.0  -400.0
2    -270    60.0  -600.0

In [238]:
df6 = df1.mul(df2, fill_value=1)

In [239]:
df6

score1  score2  score3
0    1000    20.0   200.0
1    4000    40.0   400.0
2    9000    60.0   600.0

In [240]:
df7 = df1.div(df2, fill_value=1)

In [241]:
df7

score1  score2    score3
0     0.1    20.0  0.005000
1     0.1    40.0  0.002500
2     0.1    60.0  0.001667

In [242]:
a = {'name': ['hong', 'ppl1', 'ppl2'], 'age':[20,30,25]}

In [243]:
df1 = pd.DataFrame(a)

In [244]:
df1

name  age
0  hong   20
1  ppl1   30
2  ppl2   25

In [245]:
b = {'name': ['hong', 'ppl1', 'ppl2'], 'city':['seoul', 'deajeon', 'seoul']}

In [248]:
df2 = pd.DataFrame(b)

In [249]:
df2

name     city
0  hong    seoul
1  ppl1  deajeon
2  ppl2    seoul

In [253]:
df = pd.merge(left=df1, 
              right = df2, 
              how = 'left', 
              left_on = 'name', 
              right_on ='name')

In [254]:
df

name  age     city
0  hong   20    seoul
1  ppl1   30  deajeon
2  ppl2   25    seoul

In [255]:
x1 = (df['city'] == 'seoul')

In [256]:
df[x1]

name  age   city
0  hong   20  seoul
2  ppl2   25  seoul

In [257]:
x2 = (df['city'] != 'seoul')

In [258]:
df[x2]

name  age     city
1  ppl1   30  deajeon

In [259]:
x3 = (df['age']<30)

In [260]:
df[x3]

name  age   city
0  hong   20  seoul
2  ppl2   25  seoul

In [261]:
x4 = (df['city']=='seoul') & (df['age']<30)

In [262]:
df[x4]

name  age   city
0  hong   20  seoul
2  ppl2   25  seoul

In [263]:
x5 = (df['city']=='seoul') | (df['age']<30)

In [264]:
df[x5]

name  age   city
0  hong   20  seoul
2  ppl2   25  seoul