# Numpy

In [1]:
import numpy as np

In [2]:
a = [10,20,30,40,50]

In [3]:
a

[10, 20, 30, 40, 50]

In [4]:
type(a)

list

In [5]:
b = np.array(a)

In [13]:
type(b)

numpy.ndarray

In [14]:
b

array([10, 20, 30, 40, 50])

In [7]:
print(b)

[10 20 30 40 50]


In [8]:
b.shape

(5,)

In [9]:
c = np.array ([5,4,3,2,1])

In [10]:
c

array([5, 4, 3, 2, 1])

In [11]:
b+c

array([15, 24, 33, 42, 51])

In [12]:
b + 5

array([15, 25, 35, 45, 55])

In [15]:
a+[5,4,3,2,1]

[10, 20, 30, 40, 50, 5, 4, 3, 2, 1]

In [16]:
np.sum(b)

150

In [17]:
np.mean(b)

30.0

In [18]:
np.max(b)

50

In [19]:
np.min(b)

10

In [20]:
c = b/3


In [21]:
c

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [22]:
np.round(c,1)

array([ 3.3,  6.7, 10. , 13.3, 16.7])

In [24]:
np.round(c,3)

array([ 3.333,  6.667, 10.   , 13.333, 16.667])

In [25]:
np.round(c,0)

array([ 3.,  7., 10., 13., 17.])

In [27]:
b[0]

10

In [28]:
b[-1]

50

In [29]:
b[1:3]

array([20, 30])

In [30]:
b[2:]

array([30, 40, 50])

In [31]:
np.sum(b[2:])

120

In [32]:
np.mean(b[2:])

40.0

In [34]:
b[1] = 200

In [35]:
b

array([ 10, 200,  30,  40,  50])

In [36]:
d = np.arange(5)

In [37]:
d

array([0, 1, 2, 3, 4])

In [38]:
e = np.arange(3,8)

In [39]:
e

array([3, 4, 5, 6, 7])

In [42]:
f = np.arange(3,8,2)

In [43]:
f

array([3, 5, 7])

In [44]:
g = np.zeros(5)

In [45]:
g

array([0., 0., 0., 0., 0.])

In [46]:
h = np.ones(5)

In [47]:
h

array([1., 1., 1., 1., 1.])

In [48]:
b

array([ 10, 200,  30,  40,  50])

In [49]:
bb = b

In [50]:
bb

array([ 10, 200,  30,  40,  50])

In [51]:
bb[0] = 100

In [52]:
bb

array([100, 200,  30,  40,  50])

In [53]:
b

array([100, 200,  30,  40,  50])

In [54]:
b == bb

array([ True,  True,  True,  True,  True])

In [55]:
bb = b.copy()

In [56]:
bb

array([100, 200,  30,  40,  50])

In [57]:
bb[2]= 300

In [58]:
b

array([100, 200,  30,  40,  50])

In [59]:
bb

array([100, 200, 300,  40,  50])

In [60]:
b == bb

array([ True,  True, False,  True,  True])

In [62]:
a = np.array([[10,20,30,40],[50,60,70,80]])

In [63]:
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [64]:
a.shape

(2, 4)

In [65]:
b, c = a.shape

In [66]:
b

2

In [67]:
c

4

In [70]:
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [68]:
a[0,0]

10

In [69]:
a[-1,-1]

80

In [71]:
a[1,1:]

array([60, 70, 80])

In [72]:
a[0,1] = 2

In [73]:
a

array([[10,  2, 30, 40],
       [50, 60, 70, 80]])

In [74]:
b = np.zeros((2,4))

In [75]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
c = np.ones((3,5))

In [77]:
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
c = np.arange(8)

In [79]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [80]:
c.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [81]:
 c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [82]:
c = c.reshape(2,4)

In [83]:
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [85]:
c = c.reshape(4,2)

In [86]:
c


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [87]:
c.sum()

28

In [88]:
d = c.copy()

In [90]:
d[0,0] = 10

In [94]:
d


array([[10,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7]])

In [95]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [96]:
c ==d

array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [98]:
e = np.arange(49).reshape(7,7)

In [99]:
e

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [100]:
e[:, 1:3]

array([[ 1,  2],
       [ 8,  9],
       [15, 16],
       [22, 23],
       [29, 30],
       [36, 37],
       [43, 44]])

In [101]:
e[3:, :4]

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [102]:
e[3:, :4].sum()

528

In [103]:
f = e[3:, :4].copy()

In [104]:
f

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [105]:
e[4,0]=100

In [106]:
e

array([[  0,   1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12,  13],
       [ 14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27],
       [100,  29,  30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47,  48]])

In [107]:
f

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [108]:
f.sum()

528

In [110]:
a = np.arange(5,45,5).reshape(2,4)

In [111]:
b = np.arange(20,36,2).reshape(2,4)

In [112]:
a

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [113]:
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [114]:
a+b

array([[25, 32, 39, 46],
       [53, 60, 67, 74]])

In [115]:
a - b

array([[-15, -12,  -9,  -6],
       [ -3,   0,   3,   6]])

In [116]:
b-a

array([[15, 12,  9,  6],
       [ 3,  0, -3, -6]])

In [117]:
a * b

array([[ 100,  220,  360,  520],
       [ 700,  900, 1120, 1360]])

In [118]:
a / b

array([[0.25      , 0.45454545, 0.625     , 0.76923077],
       [0.89285714, 1.        , 1.09375   , 1.17647059]])

In [119]:
a // b

array([[0, 0, 0, 0],
       [0, 1, 1, 1]])

In [120]:
a % b

array([[ 5, 10, 15, 20],
       [25,  0,  3,  6]])

In [121]:
a * 10

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

In [122]:
c = a * 10

In [123]:
c

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

In [124]:
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [125]:
bb = b.reshape(4,2)

In [126]:
bb

array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34]])

In [128]:
a

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [129]:
a @ bb   # mathmatical matrix operation

array([[1400, 1500],
       [3480, 3740]])

In [130]:
a = np.arange(1,15)

In [131]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [132]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [133]:
a == 5

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False])

In [134]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [135]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [136]:
a[a>10] = 10

In [137]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10])